pid /tmp/nginx.pid;

events {
  worker_connections  1024;
}

http {
  server {
    listen 80;
    listen [::]:80;

    server_name _;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name _;

    # TLS 1.0 and 1.1 have been deprecated, so ensure we're using the latest
    # protocol versions.
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_certificate     /etc/nginx/localhost.pem;
    ssl_certificate_key /etc/nginx/localhost.key;

    error_page 404 /errors/404.html;

    location / {
      return 404;
    }

    location /errors {
      internal;

      alias /var/www/nginx/errors/;
    }
  }
}
